# GitHub Actions Workflow
# Purpose:
# - Build and deploy the CarRentalApp MVC application
# - Automatically deploys to Azure App Service on every push to the main branch
name: Build and deploy CarRentalApp MVC to Azure

# Environment Variables
# - AZURE_WEBAPP_NAME: Name of the Azure App Service
# - DOTNET_VERSION: .NET SDK version used to build the project
env:
  AZURE_WEBAPP_NAME: carrentalapp-vp26
  DOTNET_VERSION: '9.x'

# Workflow Triggers
# - Runs automatically when code is pushed to main branch
# - Can also be triggered manually from GitHub Actions UI
on:
  push:
    branches:
      - main
  workflow_dispatch:
# Permissions
# - Read-only access to repository contents
permissions:
  contents: read
# BUILD
  # - Restores dependencies
  # - Builds the MVC application
  # - Publishes output and stores it as an artifact
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the source code from GitHub repository
      - uses: actions/checkout@v4
    # Setup the required .NET SDK version
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
    # Restore NuGet dependencies for the MVC project
      - name: Restore
        run: dotnet restore CarRentalApp/CarRentalApp.csproj
    # Build the MVC project in Release configuration
      - name: Build
        run: dotnet build CarRentalApp/CarRentalApp.csproj --configuration Release --no-restore
    # Publish the compiled application to a local folder
      - name: Publish
        run: dotnet publish CarRentalApp/CarRentalApp.csproj -c Release -o ${{env.DOTNET_ROOT}}/mvcapp

      # Upload the published output as an artifact
      # This artifact will be used in the deploy job
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mvc-app
          path: ${{env.DOTNET_ROOT}}/mvcapp

  # DEPLOY
  # - Downloads the published artifact
  # - Deploys the MVC application to Azure App Service
  deploy:
    runs-on: ubuntu-latest
    needs: build

    # Download the artifact created in the build job
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: mvc-app
          
      # Deploy the MVC application to Azure Web App
      # Authentication is handled using Azure Publish Profile
      # stored securely in GitHub Secrets
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: carrentalapp-vp26
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_CARRENTALAPP }}
          package: .
